### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by YangChangHee** [XingliangJin/MCM-LDM#3]
i used the code below, but i get this error
python demo_transfer.py --cfg ./configs/config_mld_humanml3d.yaml --cfg_assets ./configs/assets.yaml --style_motion_dir demo/style_motion --content_motion_dir demo/con^Cnt_motion --scale 2.5

error code
```
Traceback (most recent call last):
  File "/home/ubuntu/Human_Project/Paper/Motion_Transfer/MCM-LDM/demo_transfer.py", line 137, in <module>
    main()
  File "/home/ubuntu/Human_Project/Paper/Motion_Transfer/MCM-LDM/demo_transfer.py", line 71, in main
    dataset = get_datasets(cfg, logger=logger, phase="test")[0]
  File "/home/ubuntu/Human_Project/Paper/Motion_Transfer/MCM-LDM/mld/data/get_data.py", line 86, in get_datasets
    dataset = dataset_module_map[dataset_name.lower()](
  File "/home/ubuntu/Human_Project/Paper/Motion_Transfer/MCM-LDM/mld/data/HumanML3D.py", line 37, in __init__
    self._sample_set = self.get_sample_set(overrides=sample_overrides)
  File "/home/ubuntu/Human_Project/Paper/Motion_Transfer/MCM-LDM/mld/data/base.py", line 37, in get_sample_set
    return self.Dataset(split_file=split_file, **sample_params)
  File "/home/ubuntu/Human_Project/Paper/Motion_Transfer/MCM-LDM/mld/data/humanml/data/dataset.py", line 1589, in __init__
    name_list, length_list = zip(
ValueError: not enough values to unpack (expected 2, got 0)
```

please check this :)

**Comment by XingliangJin** [comment]
In this project, you have to dowload the dataset to run the demo. I suggest you follow [this project](https://github.com/Dai-Wenxun/MotionLCM?tab=readme-ov-file#-demo) to dowload a tiny Humanml3d to run the demo.

**Comment by YangChangHee** [comment]
Thank you :)
